(()=>{
const $=s=>document.querySelector(s);
function load(k,f){try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(f))}catch{return f}}
function avg(a){const z=a.filter(Number.isFinite);return z.length?z.reduce((s,x)=>s+x,0)/z.length:null}
function fmt(n){return n==null?'—':n.toFixed(1)}
function entries(){let e=load('bloom.entries.v3',null);if(!Array.isArray(e))e=load('bloom.entries.v2',[]);return Array.isArray(e)?e:[]}
function addInsight(el,title,body,meta){if([...el.querySelectorAll('.insight strong')].some(x=>x.textContent===title))return;const d=document.createElement('div');d.className='insight';d.dataset.enhanced='true';const h=document.createElement('strong');h.textContent=title;const b=document.createTextNode(body);const m=document.createElement('div');m.className='tiny';m.style.marginTop='4px';m.textContent=meta;d.append(h,b,m);el.appendChild(d)}
function signalComparison(data){const signals=new Set();data.forEach(e=>[...(e.context||[]),...(e.brain||[])].forEach(s=>signals.add(s)));const metrics=[['executive','executive functioning'],['energy','mental energy'],['activation','activation'],['mood','mood'],['reward','interest/reward'],['cognitive','cognitive clarity'],['sleep','sleep restoration']];let best=null;signals.forEach(signal=>{const yes=data.filter(e=>(e.context||[]).includes(signal)||(e.brain||[]).includes(signal));const no=data.filter(e=>!(e.context||[]).includes(signal)&&!(e.brain||[]).includes(signal));if(yes.length<3||no.length<3)return;metrics.forEach(([k,label])=>{const ya=avg(yes.map(e=>e[k])),na=avg(no.map(e=>e[k]));if(ya==null||na==null)return;const diff=ya-na;if(Math.abs(diff)<.6)return;if(!best||Math.abs(diff)>Math.abs(best.diff))best={signal,label,ya,na,diff,yn:yes.filter(e=>Number.isFinite(e[k])).length,nn:no.filter(e=>Number.isFinite(e[k])).length}})});return best}
function recurringBrain(data){const c={};data.forEach(e=>(e.brain||[]).forEach(s=>c[s]=(c[s]||0)+1));return Object.entries(c).filter(([,n])=>n>=3).sort((a,b)=>b[1]-a[1])[0]||null}
function renderEnhanced(){const el=$('#insightList');if(!el)return;el.querySelectorAll('[data-enhanced="true"]').forEach(x=>x.remove());const all=entries(),range=Number($('#rangeSelect')?.value||30),data=all.slice(-range);if(data.length<6)return;
const comp=signalComparison(data);if(comp){const direction=comp.diff<0?'lower':'higher';addInsight(el,`When “${comp.signal}” shows up`,`${comp.label[0].toUpperCase()+comp.label.slice(1)} is ${direction} on those entries: ${fmt(comp.ya)} vs ${fmt(comp.na)} when it is not logged.`,`Based on ${comp.yn} signal entries and ${comp.nn} comparison entries. Association only — Bloom is not assigning cause.`)}
const brain=recurringBrain(data);if(brain)addInsight(el,'Repeated executive / cognitive signal',`“${brain[0]}” is showing up repeatedly in your recent deep check-ins.`,`Logged ${brain[1]} times in the selected range. Worth watching for what tends to precede or accompany it.`);
const lowActHighMood=data.filter(e=>Number.isFinite(e.activation)&&Number.isFinite(e.mood)&&e.activation<=2&&e.mood>=3);if(lowActHighMood.length>=3)addInsight(el,'Low activation without equally low mood','There are repeated entries where getting started is hard even though mood is mixed or better.','That separation can be useful: low functioning is not automatically the same thing as low mood.');
const lowMoodOkayAct=data.filter(e=>Number.isFinite(e.activation)&&Number.isFinite(e.mood)&&e.mood<=2&&e.activation>=3);if(lowMoodOkayAct.length>=3)addInsight(el,'Low mood with functioning still online','There are repeated entries where mood is low but activation remains mixed or better.','Bloom keeps these separate so one does not get used as a proxy for the other.');
const weak=data.filter(e=>(e.context||[]).includes('medication felt weaker')),normal=data.filter(e=>(e.context||[]).includes('medication felt normal'));if(weak.length>=3&&normal.length>=3){const we=avg(weak.map(e=>e.executive)),ne=avg(normal.map(e=>e.executive)),wen=avg(weak.map(e=>e.energy)),nen=avg(normal.map(e=>e.energy));if(we!=null&&ne!=null&&Math.abs(we-ne)>=.5)addInsight(el,'Medication-feel entries differ',`Executive functioning averages ${fmt(we)} when medication is logged as feeling weaker, versus ${fmt(ne)} when it is logged as feeling normal.`,`Descriptive comparison only; medication response can be affected by many other factors.`);else if(wen!=null&&nen!=null&&Math.abs(wen-nen)>=.5)addInsight(el,'Medication-feel entries differ',`Mental energy averages ${fmt(wen)} when medication is logged as feeling weaker, versus ${fmt(nen)} when it is logged as feeling normal.`,`Descriptive comparison only; medication response can be affected by many other factors.`)}
}
function schedule(){setTimeout(renderEnhanced,0)}
document.querySelectorAll('.tab[data-view="patterns"]').forEach(b=>b.addEventListener('click',schedule));$('#rangeSelect')?.addEventListener('change',schedule);window.addEventListener('storage',schedule);schedule();
})();
