(()=>{
if(window.__bloomUxLoaded)return;window.__bloomUxLoaded=true;
if(!document.querySelector('link[data-bloom-ux]')){const l=document.createElement('link');l.rel='stylesheet';l.href='./ux-fixes.css?v=17';l.dataset.bloomUx='true';document.head.appendChild(l)}
const $=s=>document.querySelector(s);
function cycleData(){try{return JSON.parse(localStorage.getItem('bloom.cycle.v1')||'{}')}catch{return {}}}
function todayISO(){const d=new Date(),p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`}
function syncBleeding(){const btn=$('#bleedingBtn');if(!btn)return;const on=Array.isArray(cycleData().bleedingDays)&&cycleData().bleedingDays.includes(todayISO());btn.setAttribute('role','switch');btn.setAttribute('aria-checked',String(on));btn.innerHTML=`<span>Bleeding today</span><span class="switch-track" aria-hidden="true"><span class="switch-knob"></span></span><span class="switch-state">${on?'Yes':'No'}</span>`}
function enhanceBleeding(){const btn=$('#bleedingBtn');if(!btn||btn.closest('.bleeding-wrap'))return;const wrap=document.createElement('div');wrap.className='bleeding-wrap';btn.parentNode.insertBefore(wrap,btn);wrap.appendChild(btn);btn.classList.add('bleeding-switch');const help=document.createElement('div');help.className='bleeding-help';help.textContent='Did you have menstrual bleeding today? Switch this on for yes and off for no. “Period starts today” is only for the first day of a new period.';wrap.appendChild(help);syncBleeding();btn.addEventListener('click',()=>setTimeout(syncBleeding,0));$('#periodStartBtn')?.addEventListener('click',()=>setTimeout(syncBleeding,0))}

const simpleSymptoms=new Set(['spotting','heavy bleeding','cramps','bloating / fluid retention','headache / migraine','hot flush','night sweat','sleep disrupted','increased hunger / cravings']);
function prepareSymptomViews(){document.querySelectorAll('.cycle-symptom').forEach(b=>b.dataset.lowSimple=String(simpleSymptoms.has(b.textContent.trim())))}
function applySymptomView(low){const section=$('#cycleSymptomSection');if(!section)return;prepareSymptomViews();section.classList.toggle('low-simple-symptoms',!!low);const heading=section.querySelector('.section-label');const helper=section.querySelector('.small');if(low){if(heading)heading.textContent='Physical symptoms';if(helper)helper.textContent='Tap anything that applies. Skip the rest.'}else{if(heading)heading.textContent='Body & cycle symptoms';if(helper)helper.textContent='Optional. Pick what is actually happening today. These are tracked as body signals — Bloom does not assume hormones caused them.'}}
function ensureLowSymptomSave(){const section=$('#cycleSymptomSection');if(!section||$('#lowSaveSymptoms'))return;const btn=document.createElement('button');btn.type='button';btn.id='lowSaveSymptoms';btn.className='btn low-save-symptoms';btn.textContent='Save';btn.addEventListener('click',()=>$('#checkinForm')?.requestSubmit());section.appendChild(btn)}

function lowExtraBlock(){const low=$('#lowSection');if(!low)return null;[...low.children].filter(x=>x.classList?.contains('section-label')).forEach(x=>{if(x.textContent.trim().toLowerCase()==='anything obvious?'){x.classList.add('low-extra');x.nextElementSibling?.classList.add('low-extra')}});let panel=$('#lowCapacityPanel');if(panel)return panel;panel=document.createElement('div');panel.id='lowCapacityPanel';panel.className='low-capacity-panel';panel.innerHTML='<div class="section-label">Low-energy check-in</div><div class="domain low-capacity-domain"><h3 class="low-question">Do you have capacity for physical symptoms?</h3><div class="low-capacity-actions"><button type="button" class="btn secondary" id="lowNoSymptoms">No. Save.</button><button type="button" class="btn" id="lowYesSymptoms">Yes</button></div></div>';low.appendChild(panel);$('#lowNoSymptoms')?.addEventListener('click',()=>{$('#cycleSymptomSection')?.classList.remove('low-show-symptoms');$('#checkinForm')?.requestSubmit()});$('#lowYesSymptoms')?.addEventListener('click',()=>{applySymptomView(true);ensureLowSymptomSave();$('#cycleSymptomSection')?.classList.add('low-show-symptoms');$('#cycleSymptomSection')?.scrollIntoView({behavior:'smooth',block:'start'})});return panel}
function syncLowMode(){const form=$('#checkinForm'),note=$('#note');if(!form||!note)return;lowExtraBlock();ensureLowSymptomSave();const low=$('#lowMode')?.classList.contains('active');form.classList.toggle('low-mode',!!low);applySymptomView(low);const label=note.previousElementSibling;if(label?.classList.contains('section-label'))label.classList.add('note-label');if(low){$('#cycleSymptomSection')?.classList.remove('low-show-symptoms')}else{$('#cycleSymptomSection')?.classList.remove('low-show-symptoms')}}
function enhanceLowMode(){['lowMode','quickMode','deepMode','lowEnergyBtn','openCheckinBtn','backfillBtn','historyBackfillBtn'].forEach(id=>$('#'+id)?.addEventListener('click',()=>setTimeout(syncLowMode,0)));syncLowMode();setTimeout(syncLowMode,50)}
enhanceBleeding();enhanceLowMode();
})();
