import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';

const html = readFileSync(new URL('../index.html', import.meta.url), 'utf8');
const js = readFileSync(new URL('../app.js', import.meta.url), 'utf8');
const css = readFileSync(new URL('../design-v32.css', import.meta.url), 'utf8');
const config = JSON.parse(readFileSync(new URL('../bloom.config.json', import.meta.url), 'utf8'));

assert.match(html, /id="weekRibbon"/, 'Home must include the seven-day ribbon');
assert.match(html, /data-home-section="medication"/, 'Home medication accordion missing');
assert.match(html, /data-home-section="triggers"/, 'Home trigger accordion missing');
assert.match(html, /data-home-section="context"/, 'Home context accordion missing');
assert.match(html, /class="trigger-caption">SLEEP</, 'Trigger captions must remain visible');
assert.match(js, /button\.classList\.add\('recorded'\)/, 'Trigger save must set a visible recorded state');
assert.match(js, /if\(!primary\)return alert/, 'Trigger save must require a primary answer');
assert.match(js, /closeModal\(\);renderToday\(\);showSaved/, 'Trigger save must close and confirm immediately');
assert.match(js, /function sortTriggers\(\)/, 'Most-used trigger ordering missing');
assert.match(js, /Cycle day \$\{cd\}/, 'Cycle day must be written in full');
assert.match(js, /data-history-filter/, 'History category filters missing');
assert.doesNotMatch(js, /data-del=/, 'History must not expose later deletion');
assert.match(js, /function refreshHealth/, 'Apple Health on-open refresh missing');
assert.match(js, /window\.addEventListener\('load',\(\)=>refreshHealth\(\)\)/, 'Health refresh must run when Bloom opens');
assert.match(js, /status:total<5\?'Emerging':'Observed'/, 'Early pattern labelling missing');
assert.match(js, /function openPeriodEditor\(existing=null,prefill=today\(\)\)/, 'Retrospective Add Period flow missing');
assert.match(js, /type="date" max="\$\{today\(\)\}"/, 'Period dates must support retrospective entry and reject future dates');
assert.match(js, /Still happening — add the end date later/, 'Open-ended ongoing period control missing');
assert.match(js, /\['spotting','light','medium','heavy'\]/, 'Required flow levels missing');
assert.doesNotMatch(js, /Choose a flow level for/, 'A missed flow day must never block period completion');
assert.match(js, /Missed days can stay blank/, 'Cycle editor must explain that missed days are allowed');
assert.match(js, /dates\.filter\(date=>draft\.flowByDate\[date\]\)/, 'Only recorded flow values should be persisted');
assert.match(js, /flow-missing/, 'Calendar must distinguish an unrecorded period day');
assert.match(js, /if\(existing\?\.endDate\)/, 'Completed periods must open read-only');
assert.match(js, /data-cycle-date/, 'Calendar dates must be tappable');
assert.match(js, /prevCycleMonth/, 'Historical month navigation missing');
assert.match(js, /before=JSON\.parse\(JSON\.stringify\(cycle\)\)/, 'Period save must snapshot the cycle before saving');
assert.match(js, /showSaved\(endDate\?'Period completed':'Period saved',\(\)=>\{cycle=before;save\(\);renderCycle\(\);renderToday\(\)\}\)/, 'Period save must support immediate Undo');
assert.match(css, /@keyframes lotus-breathe/, 'Living lotus motion missing');
assert.match(css, /font-family: Didot, "Bodoni 72"/, 'Distinctive Bloom wordmark stack missing');
assert.match(css, /rgba\(255, 253, 248, \.24\)/, 'Garden atmosphere is still over-washed');
assert.ok(existsSync(new URL('../assets/bloom-garden-v34.webp', import.meta.url)), 'Garden backdrop missing');
assert.equal(config.home.visualTriggerOrder, 'most-used-first');
assert.equal(config.history.correctionModel, 'immediate-undo-only');
assert.deepEqual(config.cycle.flowLevels, ['spotting','light','medium','heavy']);
assert.equal(config.cycle.dailyFlowModel, 'heaviest-flow-reached-that-day');
assert.equal(config.cycle.flowRequiredForEveryBleedingDay, false);
assert.equal(config.cycle.missingFlowMeaning, 'not-recorded');
assert.equal(config.cycle.completedPeriodEditing, false);
assert.equal(config.cycle.ongoingPeriodEditing, true);
assert.equal(config.cycle.legacyCycleDataPreserved, true);
assert.match(js, /bloom\.trial-notes\.v1/, 'Local trial-note storage missing');
assert.match(js, /function openTrialNotes\(\)/, 'Trial amendment tracker missing');
assert.match(js, /Started 26 September · paused 4 October 2026/, 'Paused trial dates are not visible');
assert.match(js, /reviewAfter:trialEnd/, 'Trial notes must carry the review gate');
assert.match(js, /trialNotes=trialNotes\.filter/, 'Trial-note save must support immediate Undo');
assert.match(js, /homePreferences:homePrefs,trialNotes/, 'Trial notes missing from JSON export');
assert.match(js, /trialNotes=o\.trialNotes\|\|\[\]/, 'Trial notes missing from JSON import');
assert.equal(config.trial.mode, 'paused-for-adoption-blockers');
assert.equal(config.trial.paused, '2026-10-04');
assert.match(js, /function openReminderSettings\(\)/, 'Reminder setup is missing');
assert.match(js, /RRULE:FREQ=DAILY/, 'Reminder calendar must recur daily');
assert.match(js, /BEGIN:VALARM/, 'Reminder calendar must contain an alert');
assert.match(js, /URL:https:\/\/bloom-health-app\.netlify\.app/, 'Reminder must link back to Bloom');
assert.match(js, /text\/calendar;charset=utf-8/, 'Reminder download must be a calendar file');
assert.match(js, /reminderPreferences:reminderPrefs/, 'Reminder preferences missing from backup export');
assert.match(css, /\.field-row \{ grid-template-columns:1fr;/, 'Mobile time fields must stack instead of overlap');
assert.equal(config.reminders.delivery, 'recurring-ics-calendar-events');
assert.equal(config.reminders.worksWhenBrowserClosed, true);
assert.equal(config.patterns.showEmergingEarly, true);

console.log('Bloom v38 blocker regression checks passed');
