import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';

const html = readFileSync(new URL('../index.html', import.meta.url), 'utf8');
const js = readFileSync(new URL('../app.js', import.meta.url), 'utf8');
const css = readFileSync(new URL('../design-v32.css', import.meta.url), 'utf8');
const config = JSON.parse(readFileSync(new URL('../bloom.config.json', import.meta.url), 'utf8'));

assert.match(html, /id="weekRibbon"/, 'Home must include the seven-day ribbon');
assert.match(html, /data-home-section="medication"/, 'Home medication accordion missing');
assert.match(html, /data-home-section="triggers"/, 'Home trigger accordion missing');
assert.match(html, /data-home-section="context"/, 'Home context accordion missing');
assert.match(html, /class="trigger-caption">SLEEP</, 'Trigger captions must remain visible');
assert.match(js, /button\.classList\.add\('recorded'\)/, 'Trigger save must set a visible recorded state');
assert.match(js, /if\(!primary\)return alert/, 'Trigger save must require a primary answer');
assert.match(js, /closeModal\(\);renderToday\(\);showSaved/, 'Trigger save must close and confirm immediately');
assert.match(js, /function sortTriggers\(\)/, 'Most-used trigger ordering missing');
assert.match(js, /Cycle day \$\{cd\}/, 'Cycle day must be written in full');
assert.match(js, /data-history-filter/, 'History category filters missing');
assert.doesNotMatch(js, /data-del=/, 'History must not expose later deletion');
assert.match(js, /function refreshHealth/, 'Apple Health on-open refresh missing');
assert.match(js, /window\.addEventListener\('load',\(\)=>refreshHealth\(\)\)/, 'Health refresh must run when Bloom opens');
assert.match(js, /status:total<5\?'Emerging':'Observed'/, 'Early pattern labelling missing');
assert.match(js, /function openPeriodEditor\(existing=null,prefill=today\(\)\)/, 'Retrospective Add Period flow missing');
assert.match(js, /type="date" max="\$\{today\(\)\}"/, 'Period dates must support retrospective entry and reject future dates');
assert.match(js, /Still happening — add the end date later/, 'Open-ended ongoing period control missing');
assert.match(js, /\['spotting','light','medium','heavy'\]/, 'Required flow levels missing');
assert.match(js, /Choose a flow level for/, 'Every bleeding date must require a flow value');
assert.match(js, /if\(existing\?\.endDate\)/, 'Completed periods must open read-only');
assert.match(js, /data-cycle-date/, 'Calendar dates must be tappable');
assert.match(js, /prevCycleMonth/, 'Historical month navigation missing');
assert.match(js, /const before=JSON\.parse\(JSON\.stringify\(cycle\)\)/, 'Period save must support immediate Undo');
assert.match(css, /@keyframes lotus-breathe/, 'Living lotus motion missing');
assert.match(css, /font-family: Didot, "Bodoni 72"/, 'Distinctive Bloom wordmark stack missing');
assert.match(css, /rgba\(255, 253, 248, \.24\)/, 'Garden atmosphere is still over-washed');
assert.ok(existsSync(new URL('../assets/bloom-garden-v34.webp', import.meta.url)), 'Garden backdrop missing');
assert.equal(config.home.visualTriggerOrder, 'most-used-first');
assert.equal(config.history.correctionModel, 'immediate-undo-only');
assert.deepEqual(config.cycle.flowLevels, ['spotting','light','medium','heavy']);
assert.equal(config.cycle.dailyFlowModel, 'heaviest-flow-reached-that-day');
assert.equal(config.cycle.completedPeriodEditing, false);
assert.equal(config.cycle.ongoingPeriodEditing, true);
assert.equal(config.cycle.legacyCycleDataPreserved, true);
assert.match(js, /bloom\.trial-notes\.v1/, 'Local trial-note storage missing');
assert.match(js, /function openTrialNotes\(\)/, 'Trial amendment tracker missing');
assert.match(js, /Trial window: 26 September–10 October 2026/, 'Two-week trial window is not visible');
assert.match(js, /reviewAfter:trialEnd/, 'Trial notes must carry the review gate');
assert.match(js, /trialNotes=trialNotes\.filter/, 'Trial-note save must support immediate Undo');
assert.match(js, /homePreferences:homePrefs,trialNotes/, 'Trial notes missing from JSON export');
assert.match(js, /trialNotes=o\.trialNotes\|\|\[\]/, 'Trial notes missing from JSON import');
assert.equal(config.trial.mode, 'collect-notes-only');
assert.equal(config.trial.amendmentsResumeAfter, '2026-10-10');
assert.equal(config.patterns.showEmergingEarly, true);

console.log('Bloom v37 regression checks passed');
