(()=>{
const D=window.BloomData,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
D.migrateLegacy();
const today=()=>D.nowParts().localDate;
const fmtDate=iso=>new Intl.DateTimeFormat('en-GB',{weekday:'long',day:'2-digit',month:'long',year:'numeric'}).format(new Date(`${iso}T12:00:00`));
const baseline=$('#baselineView'),home=$('#homeView'),step=$('#baselineStep'),dialog=$('#flowDialog'),flow=$('#flowBody');
const safeShow=d=>{if(typeof d.showModal==='function')d.showModal();else d.setAttribute('open','')};
const save=e=>D.saveEvent(e);
function dayProgress(){const n=new Date(), mins=n.getHours()*60+n.getMinutes();return Math.max(0,Math.min(1,(mins-330)/(22*60-330)))}
function applyVisualDay(){const p=dayProgress();document.documentElement.style.setProperty('--bloom',String(.25+.75*p));const light=Math.sin(Math.PI*Math.max(0,Math.min(1,(p+.06))));document.documentElement.style.setProperty('--sun',String(.35+.65*light));}
function renderHome(){baseline.hidden=true;home.hidden=false;$('#homeDate').textContent=fmtDate(today());const c=D.cycle(),starts=[...(c.periodStarts||[])].filter(x=>x<=today()).sort();if(starts.length){const start=new Date(`${starts.at(-1)}T12:00:00`),now=new Date(`${today()}T12:00:00`),cd=Math.round((now-start)/86400000)+1;$('#cycleStatus').textContent=`Cycle day ${cd}`;}else $('#cycleStatus').textContent='';renderRecent();const now=new Date();$('#weeklyCard').hidden=now.getDay()!==0||now.getHours()<17;applyVisualDay()}
function renderRecent(){const host=$('#recent'),e=D.eventsForDate(today()).slice(-4).reverse();host.innerHTML=e.length?`<div class="small">Recent today</div>${e.map(x=>`<div class="small">${x.localTime||''} · ${x.eventType}</div>`).join('')}`:''}
function choice(label,onClick){const b=document.createElement('button');b.className='choice';b.type='button';b.textContent=label;b.onclick=onClick;return b}
function showQuestion(title,choices,helper=''){step.innerHTML='';const q=document.createElement('div');q.className='question';q.textContent=title;step.appendChild(q);if(helper){const h=document.createElement('div');h.className='small';h.textContent=helper;step.appendChild(h)}const g=document.createElement('div');g.className='choice-grid';choices.forEach(c=>g.appendChild(choice(c.label,c.onClick)));step.appendChild(g)}
function startBaseline(){home.hidden=true;baseline.hidden=false;showSleep()}
function showSleep(){showQuestion('How did you sleep?',[...'Rested|Okay|Poorly|Barely slept|I don’t remember'.split('|')].map(v=>({label:v,onClick:()=>sleepDetails(v)})))}
function sleepDetails(quality){step.innerHTML=`<div class="question">Sleep</div><div class="field"><label>Bedtime <span class="small">approximate is fine</span></label><input id="bedtime" type="time"></div><div class="field"><label>Wake time <span class="small">approximate is fine</span></label><input id="waketime" type="time"></div><button class="action" id="saveSleep">Continue</button>`;$('#saveSleep').onclick=()=>{save({eventType:'morningSleep',quality,bedtime:$('#bedtime').value||null,wakeTime:$('#waketime').value||null});showMeds()}}
function showMeds(){showQuestion('Morning meds',[{label:'Taken',onClick:()=>saveMeds('yes')},{label:'Not taken',onClick:()=>saveMeds('no')},{label:'I don’t remember',onClick:()=>saveMeds('unknown')}],'Preview shell: medication-level schedule configuration will replace this temporary aggregate screen.')}
function saveMeds(status){save({eventType:'medicationAdherence',period:'morning',status,medications:[]});showDailyState()}
function showDailyState(){showQuestion('How are you doing?', [{label:'Good',onClick:()=>dailyState('good')},{label:'Okay',onClick:()=>dailyState('okay')},{label:'Bad',onClick:()=>dailyState('bad')}])}
function dailyState(state){save({eventType:'dailyState',state});if(state==='bad')openLowEnergy();else renderHome()}
function openLowEnergy(){step.innerHTML='<div class="question">Bad day.</div><div class="small">Choose the smallest useful thing.</div><div class="choice-grid" id="lowChoices"></div>';const g=$('#lowChoices');g.append(choice('What would help right now?',()=>openNeeds(true)),choice('Sensory overload',()=>openSensory(true)),choice('Regular check-in',()=>{renderHome();openCheckIn()}),choice('Done for now',()=>renderHome()))}
function openDialog(title,body){flow.innerHTML=`<div class="brand">${title.toUpperCase()}</div>${body}`;safeShow(dialog)}
function closeDialog(){dialog.close?.();renderRecent()}
function openCheckIn(){openDialog('Check in','<div class="question">What’s going on right now?</div><div class="choice-grid" id="groups"></div>');const items=[['How I feel',()=>simpleEvent('feeling')],['How my brain is working',()=>simpleEvent('adhdExecutive')],['What my body is doing',()=>simpleEvent('periBody')],['Sensory overload',()=>openSensory()],['Context & triggers',()=>simpleEvent('periodicSnapshot')],['Regulation',()=>openRegulation()],['Needs / what would help',()=>openNeeds()],['Nothing major / just logging',()=>openNothing()]];const g=$('#groups');items.forEach(([l,f])=>g.append(choice(l,f)))}
function simpleEvent(type){save({eventType:type});closeDialog()}
function openNothing(){openDialog('Just logging','<div class="question">Anything worth noting?</div><div class="field"><textarea id="note" rows="4" placeholder="Optional"></textarea></div><button id="noteSave" class="action">Save</button>');$('#noteSave').onclick=()=>{save({eventType:'periodicSnapshot',stable:true,note:$('#note').value.trim()});closeDialog()}}
function openSensory(){openDialog('Sensory overload','<div class="question">How much?</div><div class="choice-grid" id="sev"></div>');const g=$('#sev');['Mild','Moderate','Severe','Overwhelming'].forEach(v=>g.append(choice(v,()=>sensoryTags(v))))}
function sensoryTags(severity){const tags=['sound / noise','multiple conversations','bright light / glare','visual clutter / busy screen','touch / clothing','smell / perfume / cleaning','too hot','too cold','crowding / proximity','travel / vehicle motion','too many inputs','social input','screen / notifications','food texture / taste'];openDialog('Sensory overload',`<div class="question">What’s too much?</div><div class="tag-grid">${tags.map((t,i)=>`<button type="button" class="tag" data-i="${i}" aria-pressed="false">${t}</button>`).join('')}</div><button class="action" id="sensSave">Save</button>`);$$('.tag').forEach(b=>b.onclick=()=>b.setAttribute('aria-pressed',String(b.getAttribute('aria-pressed')!=='true')));$('#sensSave').onclick=()=>{save({eventType:'sensoryOverload',severity:severity.toLowerCase(),tags:$$('.tag[aria-pressed="true"]').map(b=>b.textContent)});closeDialog()}}
function openRegulation(){openDialog('Regulation','<div class="question">Which state fits best?</div><div class="choice-grid" id="reg"></div>');const g=$('#reg');[['Activated','activated'],['Shut down','shutdown'],['Regulated','regulated']].forEach(([l,v])=>g.append(choice(l,()=>{save({eventType:'regulation',state:v});closeDialog()})))}
function openNeeds(){openDialog('What would help','<div class="question">What would help right now?</div><div class="tag-grid" id="helps"></div><button class="action" id="helpSave">Save</button>');const items=['quiet','dimmer light','be alone / space','movement','deep pressure','food / water','fresh air','lie down','body doubling','reassurance / connection','fewer decisions','stop task','change location','ask for help','set boundary','information / clarity','nothing / don’t know'];const g=$('#helps');items.forEach(t=>{const b=document.createElement('button');b.type='button';b.className='tag';b.textContent=t;b.setAttribute('aria-pressed','false');b.onclick=()=>b.setAttribute('aria-pressed',String(b.getAttribute('aria-pressed')!=='true'));g.appendChild(b)});$('#helpSave').onclick=()=>{save({eventType:'periodicSnapshot',helpNeeded:$$('#helps .tag[aria-pressed="true"]').map(b=>b.textContent)});closeDialog()}}
function quick(type){if(type==='sensory')return openSensory();if(type==='water')return quickAmount('hydration','Water','mL');if(type==='nap')return quickAmount('nap','Nap / doze','minutes');if(type==='caffeine')return quickAmount('caffeine','Caffeine / energy drink','mL');if(type==='alcohol')return quickAmount('alcohol','Alcohol','mL');if(type==='breathHolding'){save({eventType:'breathHolding'});openDialog('Breathing','<div class="question">What was happening?</div><div class="choice-grid" id="breathCtx"></div>');const g=$('#breathCtx');['Focused on task','Stressed','Sensory overload','Conflict','Driving','Screen time','Other'].forEach(v=>g.append(choice(v,()=>{save({eventType:'periodicSnapshot',contextTags:[v.toLowerCase()],linkedEvent:'breathHolding'});closeDialog()})));}}
function quickAmount(type,title,unit){openDialog(title,`<div class="question">${title}</div><div class="field"><label>Approximate ${unit}</label><input id="amount" inputmode="decimal" type="number" min="0"></div><button class="action" id="amountSave">Save</button>`);$('#amountSave').onclick=()=>{save({eventType:type,amount:Number($('#amount').value)||null,unit});closeDialog()}}
$('#checkInLotus').onclick=openCheckIn;$$('[data-quick]').forEach(b=>b.onclick=()=>quick(b.dataset.quick));
$('#weeklyOpen').onclick=()=>openDialog('Weekly review','<div class="question">Weekly review shell ready.</div><div class="small">Pattern summary and validated/non-diagnostic weekly questions will be wired to the new event store next.</div>');
setInterval(applyVisualDay,60000);
if(D.hasBaseline(today()))renderHome();else startBaseline();
})();